baseurl = "http://imogu.us"
title = "哎，蘑菇"
theme = "redlounge"
author = "nehe"
copyright = ""Copyright (c) 2008 - 2015, nehe; all rights reserved.""


[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"
