baseurl = "http://imogu.us/"
title = "哎，蘑菇"
theme = "redlounge"
author = "nehe"
copyright = "Copyright (c) 2008 - 2014, nehe; all rights reserved."
disqusShortname = "imogu"

[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"

[params]
    sidebartitle = "哎，蘑菇"
    sidebartagline = "这是什么呀?"
    categoriescss = "/css/my-categories.css"
    gaid = "UA-60028602-1"

[[menu.main]]
    name = "Blog"
    url = "/post"
[[menu.main]]
    name = "About"
    url = "/about"

[[menu.footer]]
    name = "Blog"
    url = "/post"
[[menu.footer]]
    name = "About"
    url = "/about"
